train: ./print/images/train  # путь к папке с тренировочными данными
val: ./print/images/val   # путь к папке с валидационными данными (можно использовать ту же папку, если данных мало)

nc: 3
names: ['signature', 'stamp', 'esp']  # имена классов (измените на ваши имена классов)